import { AppHeader } from "../../../frontend/src/app/components/AppHeader/AppHeader";
import { AppFooter } from "../../../frontend/src/app/components/AppFooter/AppFooter";
import "../../../frontend/src/app/global.scss";
import ReduxProvider from "../../../frontend/src/app/ReduxProvider";

export const metadata = {
  title: 'Clockmate',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <div>
            <header>
              <AppHeader />
            </header>
            <main>{children}</main>
            <footer>
              <AppFooter />
            </footer>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
