import { AppHeader } from '@/app/(root)/components/AppHeader/AppHeader';
import { AppFooter } from '@/app/(root)/components/AppFooter/AppFooter';
import './global.scss';
import AppProvider from '@/app/provider/appProvider';
import React from 'react';

export const metadata = {
  title: 'Clockmate',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <main>{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
