version: '3'
services:
  postgres-db:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PASSWORD: examplePassword
      POSTGRES_USER: exampleUser
      POSTGRES_DB: clockmate

volumes:
  db_data: