on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout des Codes
        uses: actions/checkout@v3

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          npm install
          
      - name: Build NextJS Frontend
        working-directory: frontend
        run: |
          npm run build