name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the frontend image
        if: github.ref == 'refs/heads/main'
        run: |
          docker login --username marcorehmer --password ${{ secrets.GH_PAT }} ghcr.io
          docker build ./frontend --tag ghcr.io/marcorehmer/clockmate-frontend:latest
          docker push ghcr.io/marcorehmer/clockmate-frontend:latest
      - name: Build and push the backend image
        if: github.ref == 'refs/heads/main'
        run: |
          docker login --username marcorehmer --password ${{ secrets.GH_PAT }} ghcr.io
          docker build ./backend --tag ghcr.io/marcorehmer/clockmate-backend:latest
          docker push ghcr.io/marcorehmer/clockmate-backend:latest
