import { AppHeader } from './components/AppHeader/AppHeader';
import { AppFooter } from './components/AppFooter/AppFooter';
import './global.scss';
import ReduxProvider from './ReduxProvider';

export const metadata = {
  title: 'Clockmate',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <div>
            <header>
              <AppHeader />
            </header>
            <main>{children}</main>
            <footer>
              <AppFooter />
            </footer>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
