import { AppHeader } from './components/AppHeader';
import { AppFooter } from './components/AppFooter/AppFooter';
import './global.scss';

export const metadata = {
  title: 'Clockmate',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <header>
            <AppHeader />
          </header>
          <main>{children}</main>
          <footer>
            <AppFooter />
          </footer>
        </div>
      </body>
    </html>
  );
}
